/**
 *
 * @author Emanuel
 */



package classproject;
import javax.swing.Timer;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.util.List;
import java.util.Arrays;
import java.util.ArrayList;

public class GUI_window extends javax.swing.JFrame {
    // GAME VARIABLES: -----------------------------------------------------------
    // Game 1:
    private static final int GAME1_TIME = 60;                  // Time for game round
    private static final int MG_showingTimeAfterAttempt = 500; // Time for user to see cards chosen
    private static final int MG_matchScoreIncrease = 200;      // Points given per match
    private static final int MG_timerScoreIncrease = 100;      // Points given per second after completion
    
    private static final int GAME2_TIME = 60;  // Time amount for the game 2
    private static final int GAME3_TIME = 60;  // Time amount for the game 3
    private static final int GAME4_TIME = 60;  // Time amount for the game 4
    // ----------------------------------------------------------------------------
    
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI_window.class.getName());
    public GUI_window() {
        initComponents();
        switchFrame(loginFrame);
        
        // SINGLE TIME CODE!!! ----------------------------------------------------------------------
        // Moving up frames
        game1Frame.setComponentZOrder(G1_disableCover, 0); 
        
        // Color Frames:
        G1_disableCover.setBackground(new Color(175, 157, 136, 128)); // semi-transparent main color 
        
        // Other:
        List<JLabel> MG_values = new ArrayList<>(Arrays.asList(
            G1_cardValue1, G1_cardValue2, G1_cardValue3, G1_cardValue4, G1_cardValue5, G1_cardValue6,
            G1_cardValue7, G1_cardValue8, G1_cardValue9, G1_cardValue10, G1_cardValue11, G1_cardValue12,
            G1_cardValue13, G1_cardValue14, G1_cardValue15, G1_cardValue16, G1_cardValue17, G1_cardValue18
        ));

        List<JLabel> MG_images = new ArrayList<>(Arrays.asList(
            G1_cardImage1, G1_cardImage2, G1_cardImage3, G1_cardImage4, G1_cardImage5, G1_cardImage6,
            G1_cardImage7, G1_cardImage8, G1_cardImage9, G1_cardImage10, G1_cardImage11, G1_cardImage12,
            G1_cardImage13, G1_cardImage14, G1_cardImage15, G1_cardImage16, G1_cardImage17, G1_cardImage18
        ));

        MG.setCards(MG_values, MG_images, G1_score, MG_matchScoreIncrease, MG_timerScoreIncrease, MG_showingTimeAfterAttempt);
        // -------------------------------------------------------------------------------------------
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MM_topBar = new javax.swing.JPanel();
        MM_username = new javax.swing.JLabel();
        MM_userSettingsButton = new javax.swing.JButton();
        MM_logOutButton = new javax.swing.JButton();
        MM_backToMenuButton = new javax.swing.JButton();
        game1Frame = new javax.swing.JPanel();
        G1_gameArea = new javax.swing.JPanel();
        G1_card1 = new javax.swing.JPanel();
        G1_cardValue1 = new javax.swing.JLabel();
        G1_cardImage1 = new javax.swing.JLabel();
        G1_card2 = new javax.swing.JPanel();
        G1_cardValue2 = new javax.swing.JLabel();
        G1_cardImage2 = new javax.swing.JLabel();
        G1_card3 = new javax.swing.JPanel();
        G1_cardValue3 = new javax.swing.JLabel();
        G1_cardImage3 = new javax.swing.JLabel();
        G1_card4 = new javax.swing.JPanel();
        G1_cardValue4 = new javax.swing.JLabel();
        G1_cardImage4 = new javax.swing.JLabel();
        G1_card5 = new javax.swing.JPanel();
        G1_cardValue5 = new javax.swing.JLabel();
        G1_cardImage5 = new javax.swing.JLabel();
        G1_card6 = new javax.swing.JPanel();
        G1_cardValue6 = new javax.swing.JLabel();
        G1_cardImage6 = new javax.swing.JLabel();
        G1_card7 = new javax.swing.JPanel();
        G1_cardValue7 = new javax.swing.JLabel();
        G1_cardImage7 = new javax.swing.JLabel();
        G1_card8 = new javax.swing.JPanel();
        G1_cardValue8 = new javax.swing.JLabel();
        G1_cardImage8 = new javax.swing.JLabel();
        G1_card9 = new javax.swing.JPanel();
        G1_cardValue9 = new javax.swing.JLabel();
        G1_cardImage9 = new javax.swing.JLabel();
        G1_card10 = new javax.swing.JPanel();
        G1_cardValue10 = new javax.swing.JLabel();
        G1_cardImage10 = new javax.swing.JLabel();
        G1_card11 = new javax.swing.JPanel();
        G1_cardValue11 = new javax.swing.JLabel();
        G1_cardImage11 = new javax.swing.JLabel();
        G1_card12 = new javax.swing.JPanel();
        G1_cardValue12 = new javax.swing.JLabel();
        G1_cardImage12 = new javax.swing.JLabel();
        G1_card13 = new javax.swing.JPanel();
        G1_cardValue13 = new javax.swing.JLabel();
        G1_cardImage13 = new javax.swing.JLabel();
        G1_card14 = new javax.swing.JPanel();
        G1_cardValue14 = new javax.swing.JLabel();
        G1_cardImage14 = new javax.swing.JLabel();
        G1_card15 = new javax.swing.JPanel();
        G1_cardValue15 = new javax.swing.JLabel();
        G1_cardImage15 = new javax.swing.JLabel();
        G1_card16 = new javax.swing.JPanel();
        G1_cardValue16 = new javax.swing.JLabel();
        G1_cardImage16 = new javax.swing.JLabel();
        G1_card17 = new javax.swing.JPanel();
        G1_cardValue17 = new javax.swing.JLabel();
        G1_cardImage17 = new javax.swing.JLabel();
        G1_card18 = new javax.swing.JPanel();
        G1_cardValue18 = new javax.swing.JLabel();
        G1_cardImage18 = new javax.swing.JLabel();
        G1_disableCover = new javax.swing.JPanel();
        G1_timeBoard = new javax.swing.JPanel();
        G1_timerBar = new javax.swing.JProgressBar();
        G1_startButton = new javax.swing.JButton();
        G1_scoreBoard = new javax.swing.JPanel();
        G1_score = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        game2Frame = new javax.swing.JPanel();
        game3Frame = new javax.swing.JPanel();
        game4Frame = new javax.swing.JPanel();
        mainMenuFrame = new javax.swing.JPanel();
        gamesScrollFrame = new javax.swing.JScrollPane();
        gamesPanel = new javax.swing.JPanel();
        game1 = new javax.swing.JPanel();
        MM_game1StartButton = new javax.swing.JButton();
        game1HighScore = new javax.swing.JLabel();
        game1Username = new javax.swing.JLabel();
        game1Image_ = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        game2 = new javax.swing.JPanel();
        MM_game2StartButton = new javax.swing.JButton();
        game2HighScore = new javax.swing.JLabel();
        game2Username = new javax.swing.JLabel();
        game2Image = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        game3 = new javax.swing.JPanel();
        MM_game3StartButton = new javax.swing.JButton();
        game3HighScore = new javax.swing.JLabel();
        game3Username = new javax.swing.JLabel();
        game3Image = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        game4 = new javax.swing.JPanel();
        MM_game4StartButton = new javax.swing.JButton();
        game4HighScore = new javax.swing.JLabel();
        game4Username = new javax.swing.JLabel();
        game4Image = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel48 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        MM_userSettingsPanel = new javax.swing.JPanel();
        MM_userSettingsCancelButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        MM_userSettingsPanelTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MM_usernameInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MM_passwordInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MM_passwordConfirmInput = new javax.swing.JTextField();
        MM_saveSettingsButton = new javax.swing.JButton();
        loginFrame = new javax.swing.JPanel();
        loginButtonsFrame = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        createAccountButton = new javax.swing.JButton();
        loginTitle = new javax.swing.JLabel();
        passwordConfirmInput = new javax.swing.JPasswordField();
        loginLogo = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        createAccountCancelButton = new javax.swing.JButton();
        createAccountConfirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GamesAndStuff");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MM_topBar.setBackground(new java.awt.Color(153, 135, 108));
        MM_topBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MM_username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MM_username.setForeground(java.awt.Color.white);
        MM_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MM_username.setText("<Username>");
        MM_username.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MM_topBar.add(MM_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 30));

        MM_userSettingsButton.setBackground(new java.awt.Color(200, 151, 115));
        MM_userSettingsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MM_userSettingsButton.setForeground(java.awt.Color.white);
        MM_userSettingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MM_userSettingsButton.setLabel("User Settings");
        MM_userSettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MM_userSettingsButtonMousePressed(evt);
            }
        });
        MM_topBar.add(MM_userSettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 5, -1, 40));

        MM_logOutButton.setBackground(new java.awt.Color(200, 151, 115));
        MM_logOutButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MM_logOutButton.setForeground(java.awt.Color.white);
        MM_logOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MM_logOutButton.setLabel("Log Out");
        MM_logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MM_logOutButtonMousePressed(evt);
            }
        });
        MM_topBar.add(MM_logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 5, -1, 40));

        MM_backToMenuButton.setBackground(new java.awt.Color(200, 151, 115));
        MM_backToMenuButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MM_backToMenuButton.setForeground(java.awt.Color.white);
        MM_backToMenuButton.setText("Go Back To Menu");
        MM_backToMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MM_backToMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MM_backToMenuButtonMousePressed(evt);
            }
        });
        MM_topBar.add(MM_backToMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 5, 200, 40));

        getContentPane().add(MM_topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 50));

        game1Frame.setBackground(new java.awt.Color(214, 196, 172));
        game1Frame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_gameArea.setBackground(new java.awt.Color(175, 155, 124));
        G1_gameArea.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_gameArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_card1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue1.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue1.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardValue1.setText("▲");
        G1_card1.add(G1_cardValue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card1.add(G1_cardImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 150));

        G1_card2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue2.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue2.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardValue2.setText("■");
        G1_card2.add(G1_cardValue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card2.add(G1_cardImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 150));

        G1_card3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue3.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue3.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardValue3.setText("♠");
        G1_card3.add(G1_cardValue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card3.add(G1_cardImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 100, 150));

        G1_card4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue4.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue4.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardValue4.setText("♦");
        G1_card4.add(G1_cardValue4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card4.add(G1_cardImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 100, 150));

        G1_card5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue5.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue5.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardValue5.setText("♥");
        G1_card5.add(G1_cardValue5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card5.add(G1_cardImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 100, 150));

        G1_card6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue6.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue6.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardValue6.setText("○");
        G1_card6.add(G1_cardValue6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card6.add(G1_cardImage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 100, 150));

        G1_card7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue7.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue7.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardValue7.setText("●");
        G1_card7.add(G1_cardValue7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card7.add(G1_cardImage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, 150));

        G1_card8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue8.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue8.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardValue8.setText("▼");
        G1_card8.add(G1_cardValue8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card8.add(G1_cardImage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 100, 150));

        G1_card9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue9.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue9.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardValue9.setText("⇨");
        G1_card9.add(G1_cardValue9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card9.add(G1_cardImage9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 100, 150));

        G1_card10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue10.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue10.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_card10.add(G1_cardValue10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card10.add(G1_cardImage10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 100, 150));

        G1_card11.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue11.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue11.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_card11.add(G1_cardValue11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card11.add(G1_cardImage11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 150));

        G1_card12.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue12.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue12.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_card12.add(G1_cardValue12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card12.add(G1_cardImage12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 100, 150));

        G1_card13.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue13.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue13.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_card13.add(G1_cardValue13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card13.add(G1_cardImage13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 100, 150));

        G1_card14.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue14.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue14.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_card14.add(G1_cardValue14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card14.add(G1_cardImage14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 100, 150));

        G1_card15.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue15.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue15.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_card15.add(G1_cardValue15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card15.add(G1_cardImage15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 100, 150));

        G1_card16.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue16.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue16.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_card16.add(G1_cardValue16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card16.add(G1_cardImage16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 100, 150));

        G1_card17.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue17.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue17.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_card17.add(G1_cardValue17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card17.add(G1_cardImage17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 100, 150));

        G1_card18.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_card18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_cardValue18.setFont(new java.awt.Font("Segoe UI", 0, 65)); // NOI18N
        G1_cardValue18.setForeground(new java.awt.Color(255, 102, 102));
        G1_cardValue18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_card18.add(G1_cardValue18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_cardImage18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_cardImage18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGameCard.png"))); // NOI18N
        G1_cardImage18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_cardImage18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MG_cardClicked(evt);
            }
        });
        G1_card18.add(G1_cardImage18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 150));

        G1_gameArea.add(G1_card18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 100, 150));

        game1Frame.add(G1_gameArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 720, 530));

        G1_disableCover.setBackground(new java.awt.Color(172, 157, 136));
        G1_disableCover.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        G1_disableCover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        game1Frame.add(G1_disableCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 720, 530));

        G1_timeBoard.setBackground(new java.awt.Color(153, 135, 108));
        G1_timeBoard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G1_timeBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_timerBar.setBackground(new java.awt.Color(200, 151, 115));
        G1_timerBar.setForeground(new java.awt.Color(153, 135, 108));
        G1_timerBar.setValue(30);
        G1_timeBoard.add(G1_timerBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 430, 30));

        G1_startButton.setBackground(new java.awt.Color(200, 151, 115));
        G1_startButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        G1_startButton.setForeground(java.awt.Color.white);
        G1_startButton.setText("Start Game");
        G1_startButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G1_startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                G1_startButtonMousePressed(evt);
            }
        });
        G1_timeBoard.add(G1_startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 430, 30));

        game1Frame.add(G1_timeBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 65, 440, 40));

        G1_scoreBoard.setBackground(new java.awt.Color(153, 135, 108));
        G1_scoreBoard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G1_scoreBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1_score.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        G1_score.setForeground(java.awt.Color.white);
        G1_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G1_score.setText("<score>");
        G1_scoreBoard.add(G1_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 140, 40));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Current Score: ");
        G1_scoreBoard.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        game1Frame.add(G1_scoreBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 65, 270, 40));

        getContentPane().add(game1Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        game2Frame.setBackground(new java.awt.Color(214, 196, 172));
        game2Frame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(game2Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        game3Frame.setBackground(new java.awt.Color(214, 196, 172));
        game3Frame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(game3Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        game4Frame.setBackground(new java.awt.Color(214, 196, 172));
        game4Frame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(game4Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        mainMenuFrame.setBackground(new java.awt.Color(214, 196, 172));
        mainMenuFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gamesScrollFrame.setBackground(new java.awt.Color(214, 196, 172));
        gamesScrollFrame.setForeground(new java.awt.Color(200, 151, 115));
        gamesScrollFrame.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        gamesScrollFrame.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        gamesScrollFrame.setViewportView(gamesPanel);

        gamesPanel.setBackground(new java.awt.Color(214, 196, 172));
        gamesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        game1.setBackground(new java.awt.Color(200, 151, 115));
        game1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        game1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MM_game1StartButton.setBackground(new java.awt.Color(217, 191, 157));
        MM_game1StartButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MM_game1StartButton.setForeground(java.awt.Color.white);
        MM_game1StartButton.setText("Start Game!");
        MM_game1StartButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MM_game1StartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MM_game1StartButtonMousePressed(evt);
            }
        });
        game1.add(MM_game1StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 200, 40));

        game1HighScore.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        game1HighScore.setForeground(java.awt.Color.white);
        game1HighScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        game1HighScore.setText("Not Set");
        game1.add(game1HighScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 150, 30));

        game1Username.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        game1Username.setForeground(java.awt.Color.white);
        game1Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        game1Username.setText("Not Set");
        game1Username.setToolTipText("");
        game1.add(game1Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 150, 30));

        game1Image_.setBackground(new java.awt.Color(153, 135, 108));
        game1Image_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/matchingGame.png"))); // NOI18N
        game1Image_.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        game1.add(game1Image_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 7, 145, 145));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        game1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 30, 140));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel39.setForeground(java.awt.Color.white);
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Matching Game");
        game1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 200, 60));

        jLabel89.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel89.setForeground(java.awt.Color.white);
        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel89.setText("Single Player");
        game1.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 150, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Game Type:");
        game1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 130, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Game Information:");
        game1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 300, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("User:");
        game1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 130, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Highest Score:");
        game1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 130, 30));

        gamesPanel.add(game1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 160));

        game2.setBackground(new java.awt.Color(200, 151, 115));
        game2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        game2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MM_game2StartButton.setBackground(new java.awt.Color(217, 191, 157));
        MM_game2StartButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MM_game2StartButton.setForeground(java.awt.Color.white);
        MM_game2StartButton.setText("Start Game!");
        MM_game2StartButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MM_game2StartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MM_game2StartButtonMousePressed(evt);
            }
        });
        game2.add(MM_game2StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 200, 40));

        game2HighScore.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        game2HighScore.setForeground(java.awt.Color.white);
        game2HighScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        game2HighScore.setText("----");
        game2.add(game2HighScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 150, 30));

        game2Username.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        game2Username.setForeground(java.awt.Color.white);
        game2Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        game2Username.setText("----");
        game2Username.setToolTipText("");
        game2.add(game2Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 150, 30));

        game2Image.setBackground(new java.awt.Color(153, 135, 108));
        game2Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/dotsAndBoxes.png"))); // NOI18N
        game2Image.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        game2.add(game2Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 7, 145, 145));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        game2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 30, 140));

        jLabel91.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel91.setForeground(java.awt.Color.white);
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel91.setText("2 Players");
        game2.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 150, 30));

        jLabel92.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel92.setForeground(java.awt.Color.white);
        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel92.setText("Dots and Boxes");
        game2.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 200, 60));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Game Type:");
        game2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 130, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Game Information:");
        game2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 300, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("User:");
        game2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 130, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Highest Score:");
        game2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 130, 30));

        gamesPanel.add(game2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 730, 160));

        game3.setBackground(new java.awt.Color(200, 151, 115));
        game3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        game3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MM_game3StartButton.setBackground(new java.awt.Color(217, 191, 157));
        MM_game3StartButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MM_game3StartButton.setForeground(java.awt.Color.white);
        MM_game3StartButton.setText("Start Game!");
        MM_game3StartButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MM_game3StartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MM_game3StartButtonMousePressed(evt);
            }
        });
        game3.add(MM_game3StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 200, 40));

        game3HighScore.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        game3HighScore.setForeground(java.awt.Color.white);
        game3HighScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        game3HighScore.setText("Not Set");
        game3.add(game3HighScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 150, 30));

        game3Username.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        game3Username.setForeground(java.awt.Color.white);
        game3Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        game3Username.setText("Not Set");
        game3Username.setToolTipText("");
        game3.add(game3Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 150, 30));

        game3Image.setBackground(new java.awt.Color(153, 135, 108));
        game3Image.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        game3.add(game3Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 7, 145, 145));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        game3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 30, 140));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("<game name>");
        game3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 200, 60));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel72.setForeground(java.awt.Color.white);
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("2 Players");
        game3.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 150, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Game Type:");
        game3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Game Information:");
        game3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 300, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("User:");
        game3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 130, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Highest Score:");
        game3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 130, 30));

        gamesPanel.add(game3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 730, 160));

        game4.setBackground(new java.awt.Color(200, 151, 115));
        game4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        game4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MM_game4StartButton.setBackground(new java.awt.Color(217, 191, 157));
        MM_game4StartButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MM_game4StartButton.setForeground(java.awt.Color.white);
        MM_game4StartButton.setText("Start Game!");
        MM_game4StartButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MM_game4StartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MM_game4StartButtonMousePressed(evt);
            }
        });
        game4.add(MM_game4StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 200, 40));

        game4HighScore.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        game4HighScore.setForeground(java.awt.Color.white);
        game4HighScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        game4HighScore.setText("Not Set");
        game4.add(game4HighScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 150, 30));

        game4Username.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        game4Username.setForeground(java.awt.Color.white);
        game4Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        game4Username.setText("Not Set");
        game4Username.setToolTipText("");
        game4.add(game4Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 150, 30));

        game4Image.setBackground(new java.awt.Color(153, 135, 108));
        game4Image.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        game4.add(game4Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 7, 145, 145));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        game4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 30, 140));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel48.setForeground(java.awt.Color.white);
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("2 Players");
        game4.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 150, 30));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel45.setForeground(java.awt.Color.white);
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("<game name>");
        game4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 200, 60));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Game Type:");
        game4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 130, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Game Information:");
        game4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 300, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("User:");
        game4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 130, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Highest Score:");
        game4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 130, 30));

        gamesPanel.add(game4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 730, 160));

        gamesScrollFrame.setViewportView(gamesPanel);

        mainMenuFrame.add(gamesScrollFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 765, 590));

        MM_userSettingsPanel.setBackground(new java.awt.Color(153, 135, 108));
        MM_userSettingsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MM_userSettingsCancelButton.setBackground(new java.awt.Color(200, 151, 115));
        MM_userSettingsCancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MM_userSettingsCancelButton.setForeground(java.awt.Color.white);
        MM_userSettingsCancelButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MM_userSettingsCancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MM_userSettingsCancelButton.setLabel("X");
        MM_userSettingsCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MM_userSettingsCancelButtonMousePressed(evt);
            }
        });
        MM_userSettingsPanel.add(MM_userSettingsCancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 40, 30));

        jPanel2.setBackground(new java.awt.Color(98, 82, 62));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MM_userSettingsPanelTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MM_userSettingsPanelTitle.setForeground(java.awt.Color.white);
        MM_userSettingsPanelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MM_userSettingsPanelTitle.setText("User Settings");
        jPanel2.add(MM_userSettingsPanelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 380, 20));

        MM_userSettingsPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Username:");
        MM_userSettingsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 30));

        MM_usernameInput.setBackground(new java.awt.Color(246, 228, 199));
        MM_usernameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MM_userSettingsPanel.add(MM_usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 280, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password:");
        MM_userSettingsPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        MM_passwordInput.setBackground(new java.awt.Color(246, 228, 199));
        MM_passwordInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MM_userSettingsPanel.add(MM_passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 280, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Confirm Password:");
        MM_userSettingsPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 30));

        MM_passwordConfirmInput.setBackground(new java.awt.Color(246, 228, 199));
        MM_passwordConfirmInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MM_userSettingsPanel.add(MM_passwordConfirmInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 280, 30));

        MM_saveSettingsButton.setBackground(new java.awt.Color(200, 151, 115));
        MM_saveSettingsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MM_saveSettingsButton.setForeground(java.awt.Color.white);
        MM_saveSettingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MM_saveSettingsButton.setLabel("Save Settings");
        MM_saveSettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MM_saveSettingsButtonMousePressed(evt);
            }
        });
        MM_userSettingsPanel.add(MM_saveSettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 430, 40));

        mainMenuFrame.add(MM_userSettingsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 450, 220));

        getContentPane().add(mainMenuFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        loginFrame.setBackground(new java.awt.Color(214, 196, 172));
        loginFrame.setPreferredSize(new java.awt.Dimension(400, 350));
        loginFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButtonsFrame.setBackground(new java.awt.Color(214, 196, 172));
        loginButtonsFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setBackground(new java.awt.Color(126, 195, 111));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginButton.setForeground(java.awt.Color.white);
        loginButton.setText("Log In");
        loginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginButtonMousePressed(evt);
            }
        });
        loginButtonsFrame.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 348, 35));

        createAccountButton.setBackground(new java.awt.Color(102, 153, 255));
        createAccountButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        createAccountButton.setForeground(java.awt.Color.white);
        createAccountButton.setText("Create New Account");
        createAccountButton.setToolTipText("");
        createAccountButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createAccountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createAccountButtonMousePressed(evt);
            }
        });
        loginButtonsFrame.add(createAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 348, 35));

        loginFrame.add(loginButtonsFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 100, 360, 100));

        loginTitle.setBackground(new java.awt.Color(204, 204, 204));
        loginTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginTitle.setForeground(java.awt.Color.black);
        loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitle.setText("Welcome! Please Log In");
        loginTitle.setToolTipText("");
        loginTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginFrame.add(loginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 6, 348, -1));

        passwordConfirmInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordConfirmInput.setPreferredSize(new java.awt.Dimension(64, 25));
        loginFrame.add(passwordConfirmInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 110, 348, 30));

        loginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/gameLogo.png"))); // NOI18N
        loginLogo.setText("loginSideLogo");
        loginLogo.setToolTipText("");
        loginLogo.setAlignmentY(0.0F);
        loginLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginFrame.add(loginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 198, -1));

        usernameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameInput.setToolTipText("");
        usernameInput.setPreferredSize(new java.awt.Dimension(73, 25));
        loginFrame.add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 37, 348, 30));

        passwordInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordInput.setPreferredSize(new java.awt.Dimension(64, 25));
        loginFrame.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 73, 348, 30));

        createAccountCancelButton.setBackground(new java.awt.Color(255, 153, 153));
        createAccountCancelButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        createAccountCancelButton.setForeground(java.awt.Color.white);
        createAccountCancelButton.setToolTipText("");
        createAccountCancelButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createAccountCancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccountCancelButton.setLabel("X");
        createAccountCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createAccountCancelButtonClicked(evt);
            }
        });
        loginFrame.add(createAccountCancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 150, 50, 35));

        createAccountConfirmButton.setBackground(new java.awt.Color(102, 153, 255));
        createAccountConfirmButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        createAccountConfirmButton.setForeground(java.awt.Color.white);
        createAccountConfirmButton.setToolTipText("");
        createAccountConfirmButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createAccountConfirmButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccountConfirmButton.setLabel("Register Account");
        createAccountConfirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createAccountConfirmButtonClicked(evt);
            }
        });
        loginFrame.add(createAccountConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 150, 294, 35));

        getContentPane().add(loginFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // =======================================================================================
    // ============================ GLOBAL VARIABLES =========================================
    // ---- User Control:                                                                 //||
    private String currentUser = "";                                                      //||
    private final UsersManager allUsers = new UsersManager();                             //||
                                                                                          //||
    // ---- Timers:                                                                       //||
    private int timePassed;                                                               //||
    private int fullTime;                                                                 //||
    private Timer game1Timer;                                                             //||
                                                                                          //||
    // ---- Matching Game:                                                                //||
    private final matchingGame MG = new matchingGame();                                   //||
    // =======================================================================================
    // =======================================================================================
    
    
    
    
    // SWITCH FRAME ===========================================================================
    private void switchFrame(javax.swing.JPanel target){
        // Hiding all panels
        mainMenuFrame.setVisible(false);
        MM_topBar.setVisible(false);
        loginFrame.setVisible(false);
        game1Frame.setVisible(false);
        game2Frame.setVisible(false);
        game3Frame.setVisible(false);
        game4Frame.setVisible(false);
        
        // Stop all timers
        if(game1Timer != null) game1Timer.stop();
        
        
        // Flipping between a login frame, main menu frame, or a game frame ----------------------------------
        if(target == loginFrame){
            this.setSize(580, 237);             // Make screen small for the log in section
            
            loginButtonsFrame.setVisible(true); // Showing the login frame
            usernameInput.setText("");          // Resetting username 
            passwordInput.setText("");          // Resetting password
            passwordConfirmInput.setText("");   // Resetting confirm password
            
            passwordConfirmInput.setVisible(false);       // Making password confirm input and section invis
            createAccountCancelButton.setVisible(false);  // Hiding the options for the register account
            createAccountConfirmButton.setVisible(false); // Hiding the options for the register account
        }
        else if(target == mainMenuFrame){
            this.setSize(800, 700);                               // Make screen big for anything other than the login screen
            MM_topBar.setVisible(true);                           // Show the top bar in main menu
            
            MM_username.setText("Welcome, " + currentUser + "!"); // Changing username on top bar
            MM_userSettingsPanel.setVisible(false);               // Hiding the user settings panel in case it was left open
            gamesScrollFrame.setVisible(true);                    // Showing the games panel
            MM_userSettingsButton.setVisible(true);               // Showing the user settings button
            MM_logOutButton.setVisible(true);                     // Showing the log out button
            MM_backToMenuButton.setVisible(false);                // Hiding the go back to menu since we are already there
        }
        
        // Target frame is a game frame 
        else{
            this.setSize(800, 700);                  // Make screen big for anything other than the login screen
            MM_topBar.setVisible(true);              // Show the top bar in game frames
            
            MM_userSettingsButton.setVisible(false); // Hiding user settings button
            MM_logOutButton.setVisible(false);       // Hiding log out button
            MM_backToMenuButton.setVisible(true);    // Showing the back to menu button
            
            // Setting the corresponding game reset and variables
            if(target == game1Frame){
                MM_username.setText("Matching Game"); // Changing the title to the game name
                G1_disableCover.setVisible(true);     // Showign the disable cover so player knows to start game 
                G1_timerBar.setValue(0);              // Set timer bar to zero 
                G1_timerBar.setVisible(false);        // Hide Timer bar
                G1_startButton.setVisible(true);      // Show the start button instead of timer bar
                G1_startButton.setText("Start Game!"); // Change text to reset next press
                G1_score.setText("0");                 // Sets the score back to 0
                MG.shuffle();                          // Shuffles and resets the board
            }
            else if(target == game2Frame){
                MM_username.setText("Dots and Boxes");
            }
            else if(target == game3Frame){
                MM_username.setText("<Game 3 Name>");
            }
            else if(target == game4Frame){
                MM_username.setText("<Game 4 Name>");
            }
        }
        
        // Showing target panel ONLY after everything finishes setting up
        target.setVisible(true);
    }
    // ========================================================================================
    
    
    // LOGIN FUNCTIONS ========================================================================
    private void loginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMousePressed
        // Getting inputs 
        String tempUsername = usernameInput.getText();
        String tempPassword = passwordInput.getText();

        // Checking credentials
        if(!allUsers.checkCredentials(tempUsername, tempPassword)){     
            JOptionPane.showMessageDialog(null, "Credentials are not valid.");
            passwordInput.setText("");
            return;
        }
        
        // Saving the username for later use
        currentUser = tempUsername;
        
        // Taking to the login screen
        switchFrame(mainMenuFrame);
    }//GEN-LAST:event_loginButtonMousePressed

    private void createAccountButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountButtonMousePressed
        loginButtonsFrame.setVisible(false);                    // Hide the login buttons to show confirm buttons
        
        passwordConfirmInput.setVisible(true);                 // Making password confirm input and section visible 
        createAccountCancelButton.setVisible(true);            
        createAccountConfirmButton.setVisible(true);           
    }//GEN-LAST:event_createAccountButtonMousePressed

    private void createAccountConfirmButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountConfirmButtonClicked
        // Grabbing all the inputs
        String tempUsername = usernameInput.getText();
        String tempPassword = passwordInput.getText();
        String tempPasswordConfirm = passwordConfirmInput.getText();
        
        // Check if all inputs have something
        if(tempUsername == null || tempUsername.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username cannot be empty.");
            return;
        }
        if(tempPassword == null || tempPassword.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password cannot be empty.");
            return;
        }
        if(tempPasswordConfirm == null || tempPassword.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password Confirm cannot be empty.");
            return;
        }
        
        // Check that username and password DO NOT have [,] (comma)
        if(tempUsername.contains(",") || tempPassword.contains(",") || tempPasswordConfirm.contains(",")){
            JOptionPane.showMessageDialog(null, "Inputs cannot have the comma character.");
            return;
        }
        
        // Check if username has spaces
        if(tempUsername.contains(" ")){
            JOptionPane.showMessageDialog(null, "Usernames cannot have spaces.");
            usernameInput.setText("");
            return;
        }
        
        // Check if username is valid
        if(!allUsers.validUsername(tempUsername)){
            JOptionPane.showMessageDialog(null, "This username is already taken.");
            usernameInput.setText("");
            return;
        }
        
        // Check if passwords match
        if(!tempPassword.equals(tempPasswordConfirm)){
            JOptionPane.showMessageDialog(null, "Password do not match.");
            passwordInput.setText("");
            passwordConfirmInput.setText("");
            return;
        }
        
        // Create new user -> this method saves to file too
        allUsers.addUser(tempUsername, tempPassword);
        
        // Save the current username
        currentUser = tempUsername;
        
        // Switch to mainMenu Frame
        switchFrame(mainMenuFrame);
    }//GEN-LAST:event_createAccountConfirmButtonClicked

    private void createAccountCancelButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountCancelButtonClicked
        switchFrame(loginFrame);
    }//GEN-LAST:event_createAccountCancelButtonClicked
    
// ========================================================================================
    
    
    
    
    
    
    
    
    
    
    
    
    
// MAIN MENU FUNCTIONS ====================================================================
    
    private void MM_logOutButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MM_logOutButtonMousePressed
        currentUser = "";
        switchFrame(loginFrame);
    }//GEN-LAST:event_MM_logOutButtonMousePressed

    private void MM_userSettingsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MM_userSettingsButtonMousePressed
        // Show the user settings panel and hide games panel
        gamesScrollFrame.setVisible(false);
        MM_userSettingsPanel.setVisible(true);
        
        // Erase previous data
        MM_usernameInput.setText("");
        MM_passwordInput.setText("");
        MM_passwordConfirmInput.setText("");
    }//GEN-LAST:event_MM_userSettingsButtonMousePressed

    private void MM_userSettingsCancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MM_userSettingsCancelButtonMousePressed
        // Hide the user settings panel and showing games panel
        MM_userSettingsPanel.setVisible(false);
        gamesScrollFrame.setVisible(true);
    }//GEN-LAST:event_MM_userSettingsCancelButtonMousePressed

    private void MM_saveSettingsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MM_saveSettingsButtonMousePressed
        // Check instance:
        // -> no change wanted
        // ----> C: everythig is empty 
        // ----> R: hide panel
        // -> usename change
        // ----> C: username are not empty
        // ----> R: verify username is unique, have no commas, change in files 
        // -> password change
        // ----> C: password are not empty
        // ----> R: verify passwords match, have no commas, change in files 
        
        // Grab inputs
        String tempUsername = MM_usernameInput.getText();
        String tempPassword = MM_passwordInput.getText();
        String tempConfirmPassword = MM_passwordConfirmInput.getText();
        
        // No change is needed
        if(tempUsername.trim().isEmpty() && tempPassword.trim().isEmpty() && tempConfirmPassword.trim().isEmpty()){
            MM_userSettingsPanel.setVisible(false);
            return;
        }
        
        // Username is changed
        boolean userChanged = false;
        if(!tempUsername.trim().isEmpty()){
            if(!allUsers.validUsername(tempUsername)){ // Username is not unique
                JOptionPane.showMessageDialog(null, "This username is already taken.");
                MM_usernameInput.setText("");
                return;
            }
            if(tempUsername.contains(",")){            // Username contains comma
                JOptionPane.showMessageDialog(null, "Username cannot contain commas");
                MM_usernameInput.setText("");
                return;
            }
              
            // ------ Username is valid -------
            
            // Change username object (this method also saves in file)
            allUsers.setUsername(currentUser, tempUsername);
            
            // Change temp memory after using it above
            currentUser = tempUsername;             
            userChanged = true;
        }
        
        // Password is changed (use the currentUser since its the most up to date info)
        boolean passChanged = false;
        if(!tempPassword.trim().isEmpty() || !tempConfirmPassword.trim().isEmpty()){
            if(tempPassword.contains(",") || tempConfirmPassword.contains(",")){       // Passwords contains comma
                JOptionPane.showMessageDialog(null, "Passwords cannot contain commas");
                MM_passwordInput.setText("");
                MM_passwordConfirmInput.setText("");
                return;
            }
            
            if(!tempPassword.equals(tempConfirmPassword)){                             // Passowrds do not match
                JOptionPane.showMessageDialog(null, "Passwords do not match.");
                MM_passwordInput.setText("");
                MM_passwordConfirmInput.setText("");
                return;
            }
            
            // ------ Password is valid -------
            
            // Change usesr passwords
            allUsers.setPassword(tempUsername, tempPassword);
            passChanged = true;
        }
        
        // Showing user their new username and password
        if(userChanged || passChanged){
            String message = "Changes Made:\n";
            if(userChanged)
                message = message + "New Username: " + tempUsername + "\n";
            if(passChanged)
                message = message + "New Password: " + tempPassword + "\n";
            
            
            JOptionPane.showMessageDialog(null, message); // Show the message built above
            switchFrame(mainMenuFrame);  // Send back to main menu frame to reset the username on top
        }
        else{
            // If nothing was changed, show message that nothing was changed
            JOptionPane.showMessageDialog(null, "No changes made.");
        }
        
    }//GEN-LAST:event_MM_saveSettingsButtonMousePressed

    private void MM_backToMenuButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MM_backToMenuButtonMousePressed
        switchFrame(mainMenuFrame); // Simply goes back to main menu
    }//GEN-LAST:event_MM_backToMenuButtonMousePressed

    private void MM_game1StartButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MM_game1StartButtonMousePressed
        switchFrame(game1Frame); // Switch into game 1 Frame
    }//GEN-LAST:event_MM_game1StartButtonMousePressed

    private void MM_game2StartButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MM_game2StartButtonMousePressed
        switchFrame(game2Frame); // Switch into game 2 Frame
    }//GEN-LAST:event_MM_game2StartButtonMousePressed

    private void MM_game3StartButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MM_game3StartButtonMousePressed
        switchFrame(game3Frame); // Switch into game 3 Frame
    }//GEN-LAST:event_MM_game3StartButtonMousePressed

    private void MM_game4StartButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MM_game4StartButtonMousePressed
        switchFrame(game4Frame); // Switch into game 4 Frame
    }//GEN-LAST:event_MM_game4StartButtonMousePressed

    
// ========================================================================================
  
    
    
    
    
    
    
    
    
    
    
// TIMERS FOR GAMES ==================================================================== 
    private void startG1Timer(){
        fullTime = GAME1_TIME;               // Resetting the fulltime to the time amount we want
        timePassed = 0;                      // Resettinig the timePassed to 0 so that it can start at this amount
        G1_timerBar.setMaximum(GAME1_TIME);  // Setting the max to that amount so each tick is that much
        G1_timerBar.setValue(0);             // Setting the bar to 0, as time goes, it will grow
        
        game1Timer = new Timer(1000,e->{        // Function for each tick of the timer (every 1 second)
           timePassed++;                       // Up the amount by 1
           G1_timerBar.setValue(timePassed);   // Set the bar to this amount
           
           if(timePassed >= fullTime){                // When the timer reaches Full Time:
               game1Timer.stop();                                  // Stop the timer tick
               G1_disableCover.setVisible(true);                  // Disable the game using the cover
               G1_timerBar.setVisible(false);                     // Hide the timer bar 
               G1_startButton.setVisible(true);                   // Show the start button which now says "play again!"
               JOptionPane.showMessageDialog(this, "Times Up!");  // Show a message that the game has ended 
           }
        });
        
        game1Timer.start();                   // Start the timer 
    } 
// ========================================================================================
    
    
    
// GAME 1 FUNCTIONS ==================================================================== 
    private void G1_startButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G1_startButtonMousePressed
        // Resetting game by sending back into game 1 if user finished previous game
        if(G1_startButton.getText().equals("Play Again!")){
            switchFrame(game1Frame);
            return;
        }
        
        // Start game Flow:
        G1_disableCover.setVisible(false);     // Hide the disable cover to start the game
        G1_timerBar.setVisible(true);          // Show the timer bar
        G1_startButton.setVisible(false);      // Hide the start button
        G1_startButton.setText("Play Again!"); // Change text to reset next press
        
        // Start the timer for the game when start button is pressed
        startG1Timer();
    }//GEN-LAST:event_G1_startButtonMousePressed

    private void MG_cardClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MG_cardClicked
        System.out.println("clicked a card");
        if(MG.isBusy())                  // Checking if we are currently in showing timer, return if so
            return;
        if(G1_disableCover.isVisible()) // Checking if cover is visible (usually when the game ends or is starting)
            return;
        
        System.out.println("system not busy");
        JLabel clickedLabel = (JLabel) evt.getSource(); // Getting the card that was clicked (we are really clicking on the card)
        int cardIndex = MG.getImages().indexOf(clickedLabel);
        
        System.out.println("Card clicked: " + Integer.toString(cardIndex));
        
        if(cardIndex >= 0){                                // Double checking that it won't break
            boolean gameEnded = MG.selectCard(cardIndex);  // Selecting the card which handles the visuals
            if (gameEnded) {                               // If selectCard gave T, then all matches have been found
                game1Timer.stop();
                MG.addTimeScore(fullTime-timePassed);      // Sending remaining time to add points, also updates the score
                G1_disableCover.setVisible(true);          // Covering up game
                G1_startButton.setVisible(true);           // Showing reset button 
                G1_timerBar.setVisible(false);             // Hiding game timer bar
                String message = "Completed! Points: " + G1_score; // Build message to show user
                JOptionPane.showMessageDialog(this, message);  // Show a message that the game with the points shown
            }
        }
        
    }//GEN-LAST:event_MG_cardClicked


    
    
    
    
    
    
// ========================================================================================
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI_window().setVisible(true));
      
    }

    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel G1_card1;
    private javax.swing.JPanel G1_card10;
    private javax.swing.JPanel G1_card11;
    private javax.swing.JPanel G1_card12;
    private javax.swing.JPanel G1_card13;
    private javax.swing.JPanel G1_card14;
    private javax.swing.JPanel G1_card15;
    private javax.swing.JPanel G1_card16;
    private javax.swing.JPanel G1_card17;
    private javax.swing.JPanel G1_card18;
    private javax.swing.JPanel G1_card2;
    private javax.swing.JPanel G1_card3;
    private javax.swing.JPanel G1_card4;
    private javax.swing.JPanel G1_card5;
    private javax.swing.JPanel G1_card6;
    private javax.swing.JPanel G1_card7;
    private javax.swing.JPanel G1_card8;
    private javax.swing.JPanel G1_card9;
    private javax.swing.JLabel G1_cardImage1;
    private javax.swing.JLabel G1_cardImage10;
    private javax.swing.JLabel G1_cardImage11;
    private javax.swing.JLabel G1_cardImage12;
    private javax.swing.JLabel G1_cardImage13;
    private javax.swing.JLabel G1_cardImage14;
    private javax.swing.JLabel G1_cardImage15;
    private javax.swing.JLabel G1_cardImage16;
    private javax.swing.JLabel G1_cardImage17;
    private javax.swing.JLabel G1_cardImage18;
    private javax.swing.JLabel G1_cardImage2;
    private javax.swing.JLabel G1_cardImage3;
    private javax.swing.JLabel G1_cardImage4;
    private javax.swing.JLabel G1_cardImage5;
    private javax.swing.JLabel G1_cardImage6;
    private javax.swing.JLabel G1_cardImage7;
    private javax.swing.JLabel G1_cardImage8;
    private javax.swing.JLabel G1_cardImage9;
    private javax.swing.JLabel G1_cardValue1;
    private javax.swing.JLabel G1_cardValue10;
    private javax.swing.JLabel G1_cardValue11;
    private javax.swing.JLabel G1_cardValue12;
    private javax.swing.JLabel G1_cardValue13;
    private javax.swing.JLabel G1_cardValue14;
    private javax.swing.JLabel G1_cardValue15;
    private javax.swing.JLabel G1_cardValue16;
    private javax.swing.JLabel G1_cardValue17;
    private javax.swing.JLabel G1_cardValue18;
    private javax.swing.JLabel G1_cardValue2;
    private javax.swing.JLabel G1_cardValue3;
    private javax.swing.JLabel G1_cardValue4;
    private javax.swing.JLabel G1_cardValue5;
    private javax.swing.JLabel G1_cardValue6;
    private javax.swing.JLabel G1_cardValue7;
    private javax.swing.JLabel G1_cardValue8;
    private javax.swing.JLabel G1_cardValue9;
    private javax.swing.JPanel G1_disableCover;
    private javax.swing.JPanel G1_gameArea;
    private javax.swing.JLabel G1_score;
    private javax.swing.JPanel G1_scoreBoard;
    private javax.swing.JButton G1_startButton;
    private javax.swing.JPanel G1_timeBoard;
    private javax.swing.JProgressBar G1_timerBar;
    private javax.swing.JButton MM_backToMenuButton;
    private javax.swing.JButton MM_game1StartButton;
    private javax.swing.JButton MM_game2StartButton;
    private javax.swing.JButton MM_game3StartButton;
    private javax.swing.JButton MM_game4StartButton;
    private javax.swing.JButton MM_logOutButton;
    private javax.swing.JTextField MM_passwordConfirmInput;
    private javax.swing.JTextField MM_passwordInput;
    private javax.swing.JButton MM_saveSettingsButton;
    private javax.swing.JPanel MM_topBar;
    private javax.swing.JButton MM_userSettingsButton;
    private javax.swing.JButton MM_userSettingsCancelButton;
    private javax.swing.JPanel MM_userSettingsPanel;
    private javax.swing.JLabel MM_userSettingsPanelTitle;
    private javax.swing.JLabel MM_username;
    private javax.swing.JTextField MM_usernameInput;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JButton createAccountCancelButton;
    private javax.swing.JButton createAccountConfirmButton;
    private javax.swing.JPanel game1;
    private javax.swing.JPanel game1Frame;
    private javax.swing.JLabel game1HighScore;
    private javax.swing.JLabel game1Image_;
    private javax.swing.JLabel game1Username;
    private javax.swing.JPanel game2;
    private javax.swing.JPanel game2Frame;
    private javax.swing.JLabel game2HighScore;
    private javax.swing.JLabel game2Image;
    private javax.swing.JLabel game2Username;
    private javax.swing.JPanel game3;
    private javax.swing.JPanel game3Frame;
    private javax.swing.JLabel game3HighScore;
    private javax.swing.JLabel game3Image;
    private javax.swing.JLabel game3Username;
    private javax.swing.JPanel game4;
    private javax.swing.JPanel game4Frame;
    private javax.swing.JLabel game4HighScore;
    private javax.swing.JLabel game4Image;
    private javax.swing.JLabel game4Username;
    private javax.swing.JPanel gamesPanel;
    private javax.swing.JScrollPane gamesScrollFrame;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginButtonsFrame;
    private javax.swing.JPanel loginFrame;
    private javax.swing.JLabel loginLogo;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JPanel mainMenuFrame;
    private javax.swing.JPasswordField passwordConfirmInput;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
