/**
 *
 * @author Emanuel
 */
package classproject;
import javax.swing.JOptionPane;

public class GUI_window extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI_window.class.getName());

    /**
     * Creates new form MainWindow
     */
    public GUI_window() {
        initComponents();
        switchFrame(loginFrame);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginFrame = new javax.swing.JPanel();
        loginButtonsFrame = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        createAccountButton = new javax.swing.JButton();
        loginTitle = new javax.swing.JLabel();
        passwordConfirmInput = new javax.swing.JPasswordField();
        loginLogo = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        createAccountButtonConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GamesAndStuff");
        setPreferredSize(new java.awt.Dimension(580, 237));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFrame.setBackground(new java.awt.Color(214, 196, 172));
        loginFrame.setPreferredSize(new java.awt.Dimension(400, 350));
        loginFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButtonsFrame.setBackground(new java.awt.Color(214, 196, 172));
        loginButtonsFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setBackground(new java.awt.Color(126, 195, 111));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginButton.setForeground(java.awt.Color.white);
        loginButton.setText("Log In");
        loginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginButtonMousePressed(evt);
            }
        });
        loginButtonsFrame.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 348, 35));

        createAccountButton.setBackground(new java.awt.Color(102, 153, 255));
        createAccountButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        createAccountButton.setForeground(java.awt.Color.white);
        createAccountButton.setText("Create New Account");
        createAccountButton.setToolTipText("");
        createAccountButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createAccountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createAccountButtonMousePressed(evt);
            }
        });
        loginButtonsFrame.add(createAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 348, 35));

        loginFrame.add(loginButtonsFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 100, 360, 100));

        loginTitle.setBackground(new java.awt.Color(204, 204, 204));
        loginTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginTitle.setForeground(java.awt.Color.black);
        loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitle.setText("Welcome! Please Log In");
        loginTitle.setToolTipText("");
        loginTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginFrame.add(loginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 6, 348, -1));

        passwordConfirmInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordConfirmInput.setPreferredSize(new java.awt.Dimension(64, 25));
        loginFrame.add(passwordConfirmInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 110, 348, 30));

        loginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classproject/gameLogo.png"))); // NOI18N
        loginLogo.setText("loginSideLogo");
        loginLogo.setToolTipText("");
        loginLogo.setAlignmentY(0.0F);
        loginLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginFrame.add(loginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 198, -1));

        usernameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameInput.setToolTipText("");
        usernameInput.setPreferredSize(new java.awt.Dimension(73, 25));
        loginFrame.add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 37, 348, 30));

        passwordInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordInput.setPreferredSize(new java.awt.Dimension(64, 25));
        loginFrame.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 73, 348, 30));

        createAccountButtonConfirm.setBackground(new java.awt.Color(102, 153, 255));
        createAccountButtonConfirm.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        createAccountButtonConfirm.setForeground(java.awt.Color.white);
        createAccountButtonConfirm.setToolTipText("");
        createAccountButtonConfirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createAccountButtonConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccountButtonConfirm.setLabel("Make Account");
        createAccountButtonConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createAccountButtonConfirmClicked(evt);
            }
        });
        loginFrame.add(createAccountButtonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 150, 348, 35));

        getContentPane().add(loginFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 581, 201));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // =======================================================================================
    // ============================ USERS VARIABLES ==========================================
    private String currentUser = "";                                                      //||
    private UsersManager allUsers = new UsersManager();                                   //||
    // =======================================================================================
    // =======================================================================================
    
    
    
    // SWITCH FRAME ===========================================================================
    private void switchFrame(javax.swing.JPanel target){
        // Hiding all panels
        loginFrame.setVisible(false);
        
        // Check if the target panel is the loging panel and resize
        if(target == loginFrame){
            this.setSize(580, 237); // Panel IS the login panel, make small
        }
        else{
            this.setSize(580, 600); // Panel is NOT the login panel, make big
        }
        
        // Resetting target panel if needed
        if(target == loginFrame){
            loginButtonsFrame.setVisible(true); // Showing the login frame
            usernameInput.setText("");          // Resetting username 
            passwordInput.setText("");          // Resetting password
            passwordConfirmInput.setText("");   // Resetting confirm password
            
            passwordConfirmInput.setVisible(false); // Fixing a z-issue, making inivis instead
        }
        
        
        
        // Showing target panel
        target.setVisible(true);
    }
    // ========================================================================================
    
    
    // LOGIN FUNCTIONS ========================================================================
    private void loginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMousePressed
        // TODO add your handling code here:
        System.out.println("Login Submit Button Clicked"); 
        
    }//GEN-LAST:event_loginButtonMousePressed

    private void createAccountButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountButtonMousePressed
        loginButtonsFrame.setVisible(false);                    // Hide the login buttons to show confirm buttons
        passwordConfirmInput.setVisible(true);                  // Fixing z-problem and making visible again
        System.out.println("Create Account Button Clicked");    // Temp message
    }//GEN-LAST:event_createAccountButtonMousePressed

    private void createAccountButtonConfirmClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountButtonConfirmClicked
        // Grabbing all the inputs
        String tempUsername = usernameInput.getText();
        String tempPassword = passwordInput.getText();
        String tempPasswordConfirm = passwordConfirmInput.getText();
        
        // Check if all inputs have something
        if(tempUsername == null || tempUsername.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username cannot be empty.");
            return;
        }
        if(tempPassword == null || tempPassword.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password cannot be empty.");
            return;
        }
        if(tempPasswordConfirm == null || tempPassword.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password Confirm cannot be empty.");
            return;
        }
        
        // Check that username and password DO NOT have [,] (comma)
        if(tempUsername.contains(",") || tempPassword.contains(",") || tempPasswordConfirm.contains(",")){
            JOptionPane.showMessageDialog(null, "Inputs cannot have the comma character.");
            return;
        }
        
        // Check if username has spaces
        if(tempUsername.contains(" ")){
            JOptionPane.showMessageDialog(null, "Usernames cannot have spaces.");
            usernameInput.setText("");
            return;
        }
        
        // Check if username is valid
        if(!allUsers.validUsername(tempUsername)){
            JOptionPane.showMessageDialog(null, "This username is already taken.");
            usernameInput.setText("");
            return;
        }
        
        // Check if passwords match
        if(!tempPassword.equals(tempPasswordConfirm)){
            JOptionPane.showMessageDialog(null, "Password do not match.");
            passwordInput.setText("");
            passwordConfirmInput.setText("");
            return;
        }
        
        // Create new user -> this method saves to file too
        allUsers.addUser(tempUsername, tempPassword);
        
        // Save the current username
        currentUser = tempUsername;
        
        // Switch to mainMenu Frame
        //switchFrame(mainMenuFrame);
    }//GEN-LAST:event_createAccountButtonConfirmClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI_window().setVisible(true));
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccountButton;
    private javax.swing.JButton createAccountButtonConfirm;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginButtonsFrame;
    private javax.swing.JPanel loginFrame;
    private javax.swing.JLabel loginLogo;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JPasswordField passwordConfirmInput;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
